//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public string ProjectName { get; set; }
        public decimal BilledHours { get; set; }
        public decimal BilledAmount { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsPaid { get; set; }
        public int PaymentType { get; set; }
        public bool IsArchived { get; set; }
    }
}
