//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public string Note_Comment { get; set; }
        public string Topic { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsArchived { get; set; }
        public string UserName { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
