//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Notes = new HashSet<Note>();
            this.Platforms = new HashSet<Platform>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public int CurrentStatus { get; set; }
        public Nullable<System.DateTime> EstimatedTime { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int ClientId { get; set; }
        public string Lanuage { get; set; }
        public bool IsArchived { get; set; }
        public int GroupId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Platform> Platforms { get; set; }
    }
}
