//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string ProjectName { get; set; }
        public string TaskName { get; set; }
        public bool IsBug { get; set; }
        public Nullable<System.DateTime> TotalTimeSpent { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int Current_Status { get; set; }
        public bool IsArchived { get; set; }
    }
}
